-- Check data for CUSTOMERS TABLES in DEV Schema
SELECT * FROM BRONZE_CUSTOMERS;
SELECT * FROM SILVER_CUSTOMERS;
SELECT * FROM GOLD_DIM_CUSTOMERS;

-- Check data for PRODUCTS TABLES in DEV Schema
SELECT * FROM BRONZE_PRODUCTS;
SELECT * FROM SILVER_PRODUCTS;
SELECT * FROM GOLD_DIM_PRODUCTS;

-- Check data for ORDERS_DETAILS TABLE in DEV Schema
SELECT * FROM BRONZE_ORDERS_DETAILS;
SELECT * FROM SILVER_ORDERS_DETAILS;

-- Check data for GOLD_DIM_CALENDAR
SELECT * FROM GOLD_DIM_CALENDAR;

-- Check data for ORDERS TABLE in DEV Schema
SELECT * FROM BRONZE_ORDERS;
SELECT * FROM SILVER_ORDERS;
SELECT * FROM GOLD_FACT_ORDERS;


