-- Task Bronze
CREATE OR REPLACE TASK TASK_BRONZE_ORDERS
    WAREHOUSE = COMPUTE_WH
        SCHEDULE = 'USING CRON 0 8 * * * UTC'
    AS CALL LOAD_BRONZE_ORDERS()
;

-- Task Silver
CREATE OR REPLACE TASK TASK_SILVER_ORDERS
    WAREHOUSE = COMPUTE_WH
        AFTER TASK_BRONZE_ORDERS
    AS CALL LOAD_SILVER_ORDERS()
;

-- Task Gold
CREATE OR REPLACE TASK TASK_GOLD_DIM_CALENDAR
    WAREHOUSE = COMPUTE_WH
        AFTER TASK_SILVER_ORDERS
    AS CALL GOLD_DIM_CALENDAR()
;

CREATE OR REPLACE TASK TASK_GOLD_FACT_ORDERS
    WAREHOUSE = COMPUTE_WH
        AFTER TASK_GOLD_DIM_CALENDAR
    AS CALL GOLD_FACT_ORDERS()
;


ALTER TASK TASK_GOLD_FACT_ORDERS RESUME;
ALTER TASK TASK_GOLD_DIM_CALENDAR RESUME;
ALTER TASK TASK_SILVER_ORDERS RESUME;
ALTER TASK TASK_BRONZE_ORDERS RESUME;