-- Task Bronze
CREATE OR REPLACE TASK TASK_BRONZE_PRODUCTS
    WAREHOUSE = COMPUTE_WH
        SCHEDULE = 'USING CRON 0 8 * * * UTC'
    AS CALL LOAD_BRONZE_PRODUCTS()
;

-- Task Silver
CREATE OR REPLACE TASK TASK_SILVER_PRODUCTS
    WAREHOUSE = COMPUTE_WH
        AFTER TASK_BRONZE_PRODUCTS
    AS CALL LOAD_SILVER_PRODUCTS()
;

-- Task Gold
CREATE OR REPLACE TASK TASK_GOLD_PRODUCTS
    WAREHOUSE = COMPUTE_WH
        AFTER TASK_SILVER_PRODUCTS
    AS CALL GOLD_DIM_PRODUCTS()
;

ALTER TASK TASK_GOLD_PRODUCTS RESUME;
ALTER TASK TASK_SILVER_PRODUCTS RESUME;
ALTER TASK TASK_BRONZE_PRODUCTS RESUME;


