-- Task Bronze
CREATE OR REPLACE TASK TASK_BRONZE_ORDERS_DETAILS
    WAREHOUSE = COMPUTE_WH
        SCHEDULE = 'USING CRON 0 8 * * * UTC'
    AS CALL LOAD_BRONZE_ORDERS_DETAILS()
;

-- Task Silver
CREATE OR REPLACE TASK TASK_SILVER_ORDERS_DETAILS
    WAREHOUSE = COMPUTE_WH
        AFTER TASK_BRONZE_ORDERS_DETAILS
    AS CALL LOAD_SILVER_ORDERS_DETAILS()
;


ALTER TASK TASK_SILVER_ORDERS_DETAILS RESUME;
ALTER TASK TASK_BRONZE_ORDERS_DETAILS RESUME;