-- Task Bronze
CREATE OR REPLACE TASK TASK_BRONZE_CUSTOMERS
    WAREHOUSE = COMPUTE_WH
        SCHEDULE = 'USING CRON 0 8 * * * UTC'
    AS CALL LOAD_BRONZE_CUSTOMERS()
;

-- Task Silver
CREATE OR REPLACE TASK TASK_SILVER_CUSTOMERS
    WAREHOUSE = COMPUTE_WH
        AFTER TASK_BRONZE_CUSTOMERS
    AS CALL LOAD_SILVER_CUSTOMERS()
;

-- Task Gold
CREATE OR REPLACE TASK TASK_GOLD_CUSTOMERS
    WAREHOUSE = COMPUTE_WH
        AFTER TASK_SILVER_CUSTOMERS
    AS CALL GOLD_DIM_CUSTOMERS()
;

ALTER TASK TASK_GOLD_CUSTOMERS RESUME;
ALTER TASK TASK_SILVER_CUSTOMERS RESUME;
ALTER TASK TASK_BRONZE_CUSTOMERS RESUME;